### ISSUE TITLE
support for `pull_request_target`

### ISSUE THREAD

**Issue by cjdcordeiro** [tiobe/tics-github-action#333]
https://github.com/tiobe/tics-github-action/blob/8395ef5775d182a45f2688c52b73c73edeed2332/src/main.ts#L67

and

https://github.com/tiobe/tics-github-action/blob/8395ef5775d182a45f2688c52b73c73edeed2332/src/action/decorate/action.ts#L20
---

If feasible, support for the `pull_request_target` event would be appreciated. This is because of the action's dependency on a "secret", which poses a problem for PRs where the source branch is coming from a fork. In those cases, for security purposes, we must run the action after the `pull_request_target` event, but the code above doesn't support it.

Edit: additionally, the PR comment will also be skipped for these events.
Blocks https://github.com/canonical/chisel/pull/138

**Comment by janssen-tiobe** [comment]
What do you mean with:
> Edit: additionally, the PR comment will also be skipped for these events.

Do you want no PR comment when `pull_request_target` is triggered?

**Comment by wener-tiobe** [comment]
This request is further tracked in https://redmine.tiobe.com/issues/34429
